### ISSUE TITLE
Including use Addict.RoutesHelper breaks on latest phoenix version

### ISSUE THREAD

**Issue by johandeklerk** [trenpixster/addict#62] opened 2015-10-11 14:48 UTC
== Compilation error on file web/views/page_view.ex ==
*\* (CompileError) web/views/page_view.ex:2: module Ataca.Router.Helpers is not loaded and could not be found
    (ataca) expanding macro: Ataca.Web.**using**/1
    web/views/page_view.ex:2: Ataca.PageView (module)
    (elixir) expanding macro: Kernel.use/2
    web/views/page_view.ex:2: Ataca.PageView (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

**Comment by johandeklerk** [comment] 2015-10-11 14:50
as per the documentation:

defmodule Ataca.Router do
  use Ataca.Web, :router
  use Addict.RoutesHelper

**Comment by trenpixster** [comment] 2015-10-12 15:13
Thanks for the headsup @johandeklerk

**Comment by CJPoll** [comment] 2015-10-18 23:50
It looks like the root cause is in endpoint.ex:

== Compilation error on file lib/qgen/endpoint.ex ==
** (UndefinedFunctionError) undefined function: Qgen.Router.init/1 (module Qgen.Router is not available)
    Qgen.Router.init([])
    (plug) lib/plug/builder.ex:198: Plug.Builder.init_module_plug/3
    (plug) lib/plug/builder.ex:186: anonymous fn/4 in Plug.Builder.compile/3
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug) lib/plug/builder.ex:186: Plug.Builder.compile/3
    (phoenix) expanding macro: Phoenix.Endpoint.__before_compile__/1
    lib/qgen/endpoint.ex:1: Qgen.Endpoint (module)
    (elixir) lib/kernel/parallel_compiler.ex:97: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

**Comment by CJPoll** [comment] 2015-10-19 05:18
I'm getting the same behavior, but in addition to the original error, I also get:

== Compilation error on file web/router.ex ==
*\* (CompileError) web/router.ex:3: module Addict.RoutesHelper is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    web/router.ex:3: Qgen.Router (module)
    (elixir) lib/kernel/parallel_compiler.ex:97: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

**Comment by trenpixster** [comment] 2015-10-20 11:55
@CJPoll @johandeklerk was that from the `master` branch or an actual release?

**Comment by trenpixster** [comment] 2015-11-12 10:33
The issue here is that most likely you've created a pipeline named `:addict` in the router, something like:

``` elixir
  pipeline :addict do
   ....
  end
```

If we rename it to anything else, it should work. Closing this for now, but if this is not the issue, feel free to reopen.

**Closed as completed** 2015-11-12 10:34 UTC
